os: Visual Studio 2013

environment:
  global:
    PROJECT_NAME: sass

  matrix:
      - TARGET: x86_64-pc-windows-msvc
        CHANNEL: stable
      - TARGET: i686-pc-windows-msvc
        CHANNEL: stable

install:
  # Install Rust and Cargo
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V
  - git submodule update --init

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

build: false

test_script:
  - cargo test
